apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/KhacThien0808/Infra-GitOps-Test'
      revision: HEAD
      directories:
      - path: 'charts/*'
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/KhacThien0808/Infra-GitOps-Test'
        targetRevision: HEAD
        path: '{{path}}'
        plugin:
          name: helmfile

      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true