repositories:
  - name: jetstack
    url: https://charts.jetstack.io
releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version:  1.17.0
    values:
      - values.yaml
